language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t walkingcrows/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true walkingcrows/react-test npm test -- --coverage

after_success:
  - docker build -t walkingcrows/multi-client ./client
  - docker build -t walkingcrows/multi-nginx ./nginx
  - docker build -t walkingcrows/multi-server ./server
  - docker build -t walkingcrows/multi-worker ./worker
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker push walkingcrows/multi-client
  - docker push walkingcrows/multi-nginx
  - docker push walkingcrows/multi-server
  - docker push walkingcrows/multi-worker
